//
//  WordLists.swift
//  WortDesTages
//
//  Created by Raphael Schwarz on 14.03.25.
//

import Foundation

let wirtschaftsWörterListe: [(word: String, definition: String)] = [
    ("Kapitalismus", "Ein Wirtschaftssystem, das auf Privatbesitz und Gewinnstreben basiert."),
    ("Inflation", "Eine allgemeine Erhöhung der Preise über einen bestimmten Zeitraum."),
    ("Volatilität", "Die Schwankungsintensität eines Wertes, z. B. bei Aktien."),
    ("Hedging", "Eine Strategie zur Absicherung gegen Preisbewegungen, häufig in der Finanzwelt verwendet."),
    ("Liquidität", "Die Fähigkeit, ein Vermögenswert schnell und ohne großen Preisverlust zu verkaufen."),
    ("Diversifikation", "Die Verteilung von Investitionen auf verschiedene Anlageklassen zur Risikominderung."),
    ("Rendite", "Der Gewinn oder Ertrag einer Geldanlage, meist in Prozent pro Jahr angegeben."),
    ("Korrelation", "Ein statistisches Maß für den Zusammenhang zwischen zwei oder mehreren Variablen."),
    ("Inflation", "Der allgemeine Anstieg des Preisniveaus von Waren und Dienstleistungen über einen bestimmten Zeitraum."),
    ("Deflation", "Der Rückgang des allgemeinen Preisniveaus von Waren und Dienstleistungen."),
    ("Bilanzen", "Finanzielle Dokumente, die die Vermögenslage und die Schulden eines Unternehmens darstellen."),
    ("Zinseszins", "Die Berechnung von Zinsen auf bereits erzielte Zinsen, wodurch das Kapital exponentiell wächst."),
    ("Marktkapitalisierung", "Der Gesamtwert eines Unternehmens an der Börse, berechnet durch Multiplikation des Aktienkurses mit der Anzahl der ausstehenden Aktien."),
    ("Indexfonds", "Ein Investmentfonds, der einen bestimmten Marktindex nachbildet und dessen Leistung verfolgt."),
    ("Aktienoption", "Ein Vertrag, der dem Käufer das Recht gibt, Aktien zu einem festgelegten Preis innerhalb eines bestimmten Zeitraums zu kaufen oder zu verkaufen."),
    ("Kapitalstruktur", "Die Aufteilung eines Unternehmens zwischen Eigenkapital und Fremdkapital."),
    ("Asset Allocation", "Die strategische Verteilung von Vermögenswerten in verschiedene Anlageklassen."),
    ("Kapitalkosten", "Die Kosten, die ein Unternehmen für die Beschaffung von Kapital aufwenden muss, entweder durch Eigenkapital oder Fremdkapital."),
    ("Transparenz", "Die Offenlegung von Informationen über die Geschäftstätigkeit und Finanzen eines Unternehmens."),
    ("Underperformance", "Die schlechtere Leistung eines Investments im Vergleich zu einem Referenzmaßstab oder -index."),
    ("Overvaluation", "Eine Situation, in der der Marktpreis eines Vermögenswerts über seinem tatsächlichen Wert liegt."),
    ("Fundamentalanalyse", "Eine Methode zur Bewertung von Wertpapieren basierend auf wirtschaftlichen und finanziellen Faktoren."),
    ("Technische Analyse", "Eine Methode zur Bewertung von Wertpapieren durch die Analyse von Statistiken, die von Marktaktivitäten erzeugt werden."),
    ("Bull-Markt", "Ein Markt, in dem die Preise steigen oder voraussichtlich steigen werden."),
    ("Bär-Markt", "Ein Markt, in dem die Preise fallen oder voraussichtlich fallen werden."),
    ("Rating", "Eine Bewertung der Kreditwürdigkeit eines Unternehmens oder eines Wertpapiers."),
    ("Anleihe", "Ein festverzinsliches Wertpapier, das als Darlehen an eine Institution betrachtet wird."),
    ("Crowdfunding", "Eine Finanzierungsform, bei der viele Menschen kleine Beträge investieren, um ein Projekt oder Unternehmen zu unterstützen."),
    ("Peer-to-Peer Lending", "Eine Form des direkten Kreditvergabe zwischen Einzelpersonen, oft über Online-Plattformen."),
    ("Volumen", "Die Menge an gehandelten Wertpapieren in einem bestimmten Zeitraum."),
    ("Dividende", "Ein Teil des Gewinns eines Unternehmens, der an die Aktionäre ausgeschüttet wird."),
    ("Marge", "Der Unterschied zwischen den Gesamterlösen und den Gesamtkosten eines Unternehmens."),
    ("Leverage", "Die Verwendung von Fremdkapital zur Erhöhung der potenziellen Rendite einer Anlage."),
    ("Risiko", "Die Möglichkeit eines Verlustes oder einer negativen Abweichung von erwarteten Ergebnissen."),
    ("Buchwert", "Der Wert eines Unternehmens, wie er in der Bilanz ausgewiesen ist, abzüglich der Verbindlichkeiten."),
    ("Option", "Ein Finanzinstrument, das dem Käufer das Recht, aber nicht die Pflicht gibt, einen Vermögenswert zu einem festgelegten Preis zu kaufen oder zu verkaufen."),
    ("Future", "Ein Vertrag, der den Kauf oder Verkauf eines Vermögenswerts zu einem zukünftigen Zeitpunkt zu einem festgelegten Preis vereinbart."),
    ("Benchmark", "Ein Standard oder eine Referenzmaßnahme, gegen die die Leistung eines Investments bewertet wird."),
    ("Sektor", "Ein bestimmter Bereich der Wirtschaft oder des Marktes, in den Unternehmen unterteilt werden können"),
    ("Portfolio", "Eine Sammmlung von Investitionen, die ein Anleger hält."),
    ("Risikomanagement", "Der Prozess der Identifizierung, Analyse und Reaktion auf potenzielle Risiken in einer Investitionsstrategie."),
    ("Währungsrisiko", "Das Risiko von Verlusten aufgrund von Wechselkursänderungen."),
    ("Marktanalyse", "Die Untersuchung und Bewertung von Marktbedingungen und -trends."),
    ("Kaufkraft", "Die Fähigkeit von Währungen, Waren und Dienstleistungen zu kaufen."),
    ("Empfehlung", "Ein Ratschlag oder Hinweis zur Entscheidung über den Kauf oder Verkauf von Wertpapieren."),
    ("Börsengang (IPO)", "Der Prozess, durch den ein Unternehmen seine Aktien zum ersten Mal an der Börse anbietet."),
    ("Fairer Wert", "Der geschätzte Preis eines Vermögenswerts basierend auf einer grundlegenden Analyse."),
    ("Kurs-Gewinn-Verhältnis (KGV)", "Ein Verhältnis, das den aktuellen Aktienkurs eines Unternehmens im Verhältnis zu seinem Gewinn pro Aktie zeigt."),
    ("Kapitalgewinne", "Die Gewinne, die aus dem Verkauf eines Vermögenswerts erzielt werden, der im Wert gestiegen ist."),
    ("Anlageziel", "Ein spezifisches Ziel, das ein Anleger mit seinen Investitionen erreichen möchte."),
    ("Nachhaltige Investitionen", "Investitionen, die Umwelt-, Sozial- und Governance-Faktoren berücksichtigen."),
    ("Betriebliche Effizienz", "Die Fähigkeit eines Unternehmens, Ressourcen optimal zu nutzen, um Gewinne zu maximieren."),
    ("Wirtschaftswachstum", "Die Zunahme der wirtschaftlichen Aktivität und des Produktionspotenzials einer Volkswirtschaft."),
    ("Märkteffizienz", "Die Hypothese, dass alle verfügbaren Informationen in den Preisen von Vermögenswerten reflektiert sind."),
    ("Aktionär", "Eine Person oder Institution, die Aktien eines Unternehmens besitzt."),
    ("Holdinggesellschaft", "Ein Unternehmen, dessen Hauptzweck in der Verwaltung von Beteiligungen an anderen Unternehmen besteht."),
    ("Dividendenrendite", "Das Verhältnis der Dividende einer Aktie zu ihrem aktuellen Preis, ausgedrückt in Prozent."),
    ("Ertragswert", "Der Wert eines Vermögenswertes, basierend auf den zukünftigen Erträgen, die er generieren wird."),
    ("Wachstumsaktien", "Aktien von Unternehmen, die überdurchschnittlich schnell wachsen und investiert werden, um anhaltendes Wachstum zu bieten."),
    ("Value-Aktien", "Aktien, die als unterbewertet angesehen werden und ein großes Potenzial für Kurssteigerungen bieten."),
    ("Rückstellung", "Ein Betrag, der zur Deckung künftiger Verpflichtungen oder erwarteter Verluste reserviert wird."),
    ("Eigenkapital", "Das Kapital, das von den Eigentümern eines Unternehmens zur Verfügung gestellt wird."),
    ("Fremdkapital", "Kapital, das einem Unternehmen von externen Kreditgebern zur Verfügung gestellt wird, das in der Regel zurückgezahlt werden muss."),
    ("Einnahmequellen", "Die verschiedenen Methoden, mit denen ein Unternehmen Einnahmen generiert."),
    ("Cashflow", "Der Nettobetrag der liquiden Mittel, der in einem bestimmten Zeitraum in ein Unternehmen hineinfließt oder herausfließt."),
    ("Depot", "Ein Konto, auf dem Wertpapiere und andere Investitionen gehalten werden."),
    ("Finanzierungsrunde", "Ein Prozess, bei dem ein Unternehmen Kapital von Investoren sammelt, oft in mehreren Phasen.")
]

let geschichteWörterListe: [(word: String, definition: String)] = [
    ("Renaissance", "Eine kulturelle Bewegung des 14.–17. Jahrhunderts."),
    ("Aufklärung", "Eine intellektuelle Bewegung im 17. und 18. Jahrhundert."),
    ("Imperialismus", "Die Politik eines Landes, seine Macht und seinen Einfluss über andere Länder durch Kolonialisierung oder militärische Eroberung auszubauen."),
    ("Aufklärung", "Eine intellektuelle Bewegung des 17. und 18. Jahrhunderts, die Vernunft und Wissen über Tradition und Glauben stellte."),
    ("Kolonialismus", "Die Praxis der Kontrolle und Besiedlung fremder Gebiete durch eine Nation."),
    ("Revolution", "Ein radikaler und schneller Wandel eines politischen Systems oder gesellschaftlicher Strukturen."),
    ("Feudalismus", "Ein soziales und wirtschaftliches System im Mittelalter, in dem Landbesitz und Treueverhältnisse zentral waren."),
    ("Bürgerkrieg", "Ein interner Krieg zwischen verschiedenen Gruppen innerhalb eines Landes."),
    ("Humanismus", "Eine intellektuelle Bewegung, die den Menschen und seine Fähigkeiten in den Mittelpunkt stellte, besonders während der Renaissance."),
    ("Totalitarismus", "Ein politisches System, das die totale Kontrolle über das öffentliche und private Leben der Bürger ausübt."),
    ("Konstitution", "Ein Dokument, das die grundlegenden Prinzipien und Regeln einer Regierung oder Organisation festlegt."),
    ("Moderner Staat", "Ein politisches Gebilde mit definierter territorialer Grenze, einer stabilen Regierung und einem anerkannten Rechtssystem."),
    ("Industrialismus", "Ein Wirtschafts- und Gesellschaftsmodell, das auf industrieller Produktion basiert und die Mechanisierung und Massenproduktion betont."),
    ("Kaltes Krieg", "Eine Zeit geopolitischer Spannungen zwischen den USA und der Sowjetunion nach dem Zweiten Weltkrieg."),
    ("Diktatur", "Eine Regierungsform, in der eine Person oder eine kleine Gruppe die absolute Kontrolle hat und politische Opposition unterdrückt."),
    ("Sozialismus", "Ein politisches und wirtschaftliches System, das soziale Eigentumsformen und die Umverteilung des Reichtums fördert."),
    ("Nationalismus", "Eine Ideologie, die das Interesse und die Identität einer Nation über andere legt."),
    ("Sklaverei", "Ein System, in dem Menschen als Eigentum anderer Menschen behandelt und zur Arbeit gezwungen werden."),
    ("Mittelalter", "Eine historische Periode in Europa, die grob vom 5. bis zum 15. Jahrhundert reicht."),
    ("Kreuzzüge", "Militärische Expeditionen, die im Mittelalter von europäischen Christen unternommen wurden, um das Heilige Land zu erobern."),
    ("Entkolonialisierung", "Der Prozess, durch den koloniale Staaten ihre Unabhängigkeit erlangen."),
    ("Wirtschaftskrise", "Eine Phase signifikanter wirtschaftlicher Stagnation oder Rückgangs, oft verbunden mit hohen Arbeitslosenzahlen."),
    ("Sumerer", "Eine der frühesten Zivilisationen, die im südlichen Mesopotamien lebte und für ihre Erfindungen wie die Keilschrift bekannt ist."),
    ("Pharao", "Der Titel für die monarchischen Herrscher des alten Ägyptens, oft als göttlich betrachtet."),
    ("Konquista", "Die spanische Eroberung und Kolonisierung von großen Teilen Amerikas im 16. Jahrhundert."),
    ("Römisches Recht", "Das Rechtssystem, das im antiken Rom entstanden ist und bis heute Einfluss auf viele moderne Rechtssysteme hat."),
    ("Byzantinisches Reich", "Der östliche Teil des Römischen Reiches, der nach dem Fall des Weströmischen Reiches fortbestand und für seine kulturellen Beiträge bekannt ist."),
    ("Reformation", "Eine religiöse Bewegung im 16. Jahrhundert, die zur Spaltung der römisch-katholischen Kirche und zur Entstehung des Protestantismus führte."),
    ("Absolutistische Monarchie", "Eine Regierungsform, in der der Monarch nahezu uneingeschränkte Macht hat und durch keine Gesetze oder Institutionen eingeschränkt ist."),
    ("Feudalordnung", "Ein gesellschaftliches System, das im Mittelalter vorherrschte, gekennzeichnet durch eine Hierarchie von Landbesitzern und Lehnsmännern.")
]

let politikWörterListe: [(word: String, definition: String)] = [
    ("Demokratie", "Ein Regierungssystem, in dem das Volk mitbestimmt."),
    ("Diktatur", "Ein Regierungssystem, in dem eine Einzelperson oder Gruppe absolute Macht hat.")
]
