//
//  WordLists.swift
//  WortDesTages
//
//  Created by Raphael Schwarz on 14.03.25.
//

import Foundation

let wirtschaftsWörterListe: [(word: String, pronunciation: String, definition: String)] = [
    ("Kapitalismus",             "ka·pi·ta·LIS·mus",              "Ein Wirtschaftssystem, das auf Privatbesitz und Gewinnstreben basiert."),
    ("Inflation",                "in·fla·TSI·on",                 "Eine allgemeine Erhöhung der Preise über einen bestimmten Zeitraum."),
    ("Volatilität",              "vo·la·ti·li·TÄÄHT",             "Die Schwankungsintensität eines Wertes, z. B. bei Aktien."),
    ("Hedging",                  "HED·dsching",                   "Eine Strategie zur Absicherung gegen Preisbewegungen, häufig in der Finanzwelt verwendet."),
    ("Liquidität",               "li·kwi·di·TÄÄHT",               "Die Fähigkeit, einen Vermögenswert schnell und ohne großen Preisverlust zu verkaufen."),
    ("Diversifikation",          "di·ver·si·fi·ka·TSI·on",        "Die Verteilung von Investitionen auf verschiedene Anlageklassen zur Risikominderung."),
    ("Rendite",                  "ren·DI·te",                     "Der Gewinn oder Ertrag einer Geldanlage, meist in Prozent pro Jahr angegeben."),
    ("Korrelation",              "ko·re·la·TSI·on",               "Ein statistisches Maß für den Zusammenhang zwischen zwei oder mehreren Variablen."),
    ("Deflation",                "de·fla·TSI·on",                 "Der Rückgang des allgemeinen Preisniveaus von Waren und Dienstleistungen."),
    ("Bilanzen",                 "bi·LAN·zen",                    "Finanzielle Dokumente, die die Vermögenslage und die Schulden eines Unternehmens darstellen."),
    ("Zinseszins",               "ZIN·ses·tzins",                 "Die Berechnung von Zinsen auf bereits erzielte Zinsen, wodurch das Kapital exponentiell wächst."),
    ("Marktkapitalisierung",     "MARKT·ka·pi·ta·li·SI·rung",     "Der Gesamtwert eines Unternehmens an der Börse, berechnet durch Multiplikation des Aktienkurses mit der Anzahl der ausstehenden Aktien."),
    ("Indexfonds",               "IN·deks·fon",                   "Ein Investmentfonds, der einen bestimmten Marktindex nachbildet und dessen Leistung verfolgt."),
    ("Aktienoption",             "AK·tsi·en·op·tsi·on",           "Ein Vertrag, der dem Käufer das Recht gibt, Aktien zu einem festgelegten Preis innerhalb eines bestimmten Zeitraums zu kaufen oder zu verkaufen."),
    ("Kapitalstruktur",          "ka·pi·TAL·struk·tur",           "Die Aufteilung eines Unternehmens zwischen Eigenkapital und Fremdkapital."),
    ("Asset Allocation",         "AS·set al·lo·KÄI·schn",         "Die strategische Verteilung von Vermögenswerten in verschiedene Anlageklassen."),
    ("Kapitalkosten",            "ka·pi·TAL·kos·ten",             "Die Kosten, die ein Unternehmen für die Beschaffung von Kapital aufwenden muss."),
    ("Transparenz",              "trans·pa·RÄNTS",                "Die Offenlegung von Informationen über die Geschäftstätigkeit und Finanzen eines Unternehmens."),
    ("Underperformance",         "AN·der·per·FOR·mens",           "Die schlechtere Leistung eines Investments im Vergleich zu einem Referenzmaßstab oder -index."),
    ("Overvaluation",            "O·ver·val·ju·Ä·schn",           "Eine Situation, in der der Marktpreis eines Vermögenswerts über seinem tatsächlichen Wert liegt."),
    ("Fundamentalanalyse",       "fun·da·men·TAL·a·na·ly·se",     "Eine Methode zur Bewertung von Wertpapieren basierend auf wirtschaftlichen und finanziellen Faktoren."),
    ("Technische Analyse",       "TECH·ni·sche a·NA·ly·se",       "Eine Methode zur Bewertung von Wertpapieren durch die Analyse von Statistiken aus Marktaktivitäten."),
    ("Bull-Markt",               "BUL·markt",                     "Ein Markt, in dem die Preise steigen oder voraussichtlich steigen werden."),
    ("Bär-Markt",                "BÄÄR·markt",                    "Ein Markt, in dem die Preise fallen oder voraussichtlich fallen werden."),
    ("Rating",                   "RÄI·ting",                      "Eine Bewertung der Kreditwürdigkeit eines Unternehmens oder eines Wertpapiers."),
    ("Anleihe",                  "AN·lei·he",                     "Ein festverzinsliches Wertpapier, das als Darlehen an eine Institution betrachtet wird."),
    ("Crowdfunding",             "KRAUD·fan·ding",                "Eine Finanzierungsform, bei der viele Menschen kleine Beträge investieren, um ein Projekt zu unterstützen."),
    ("Peer-to-Peer Lending",     "PIER·tu·pier LEN·ding",         "Eine Form der direkten Kreditvergabe zwischen Einzelpersonen, oft über Online-Plattformen."),
    ("Volumen",                  "vo·LU·men",                     "Die Menge an gehandelten Wertpapieren in einem bestimmten Zeitraum."),
    ("Dividende",                "di·vi·DEN·de",                  "Ein Teil des Gewinns eines Unternehmens, der an die Aktionäre ausgeschüttet wird."),
    ("Marge",                    "MAR·sche",                      "Der Unterschied zwischen den Gesamterlösen und den Gesamtkosten eines Unternehmens."),
    ("Leverage",                 "LE·ve·ridsch",                  "Die Verwendung von Fremdkapital zur Erhöhung der potenziellen Rendite einer Anlage."),
    ("Risiko",                   "RI·si·ko",                      "Die Möglichkeit eines Verlustes oder einer negativen Abweichung von erwarteten Ergebnissen."),
    ("Buchwert",                 "BUCH·wert",                     "Der Wert eines Unternehmens, wie er in der Bilanz ausgewiesen ist, abzüglich der Verbindlichkeiten."),
    ("Option",                   "op·TSI·on",                     "Ein Finanzinstrument, das dem Käufer das Recht, aber nicht die Pflicht gibt, einen Vermögenswert zu kaufen oder zu verkaufen."),
    ("Future",                   "FJUU·tschö",                    "Ein Vertrag, der den Kauf oder Verkauf eines Vermögenswerts zu einem zukünftigen Zeitpunkt zu einem festgelegten Preis vereinbart."),
    ("Benchmark",                "BENCH·mark",                    "Ein Standard oder eine Referenzmaßnahme, gegen die die Leistung eines Investments bewertet wird."),
    ("Sektor",                   "SEK·tor",                       "Ein bestimmter Bereich der Wirtschaft, in den Unternehmen unterteilt werden können."),
    ("Portfolio",                "port·FO·li·o",                  "Eine Sammlung von Investitionen, die ein Anleger hält."),
    ("Risikomanagement",         "RI·si·ko·ma·nä·dsch·ment",      "Der Prozess der Identifizierung, Analyse und Reaktion auf potenzielle Risiken in einer Investitionsstrategie."),
    ("Währungsrisiko",           "WÄH·rungs·ri·si·ko",            "Das Risiko von Verlusten aufgrund von Wechselkursänderungen."),
    ("Marktanalyse",             "MARKT·a·na·ly·se",              "Die Untersuchung und Bewertung von Marktbedingungen und -trends."),
    ("Kaufkraft",                "KAUF·kraft",                    "Die Fähigkeit von Währungen, Waren und Dienstleistungen zu kaufen."),
    ("Börsengang (IPO)",         "BÖR·sen·gang",                  "Der Prozess, durch den ein Unternehmen seine Aktien zum ersten Mal an der Börse anbietet."),
    ("Fairer Wert",              "FÄI·rer WERT",                  "Der geschätzte Preis eines Vermögenswerts basierend auf einer grundlegenden Analyse."),
    ("Kurs-Gewinn-Verhältnis",   "KURS·ge·win·fer·häl·tnis",      "Ein Verhältnis, das den aktuellen Aktienkurs eines Unternehmens im Verhältnis zu seinem Gewinn pro Aktie zeigt."),
    ("Kapitalgewinne",           "ka·pi·TAL·ge·win·ne",           "Die Gewinne, die aus dem Verkauf eines Vermögenswerts erzielt werden, der im Wert gestiegen ist."),
    ("Nachhaltige Investitionen","NACH·hal·ti·ge in·ves·ti·TSI·o·nen", "Investitionen, die Umwelt-, Sozial- und Governance-Faktoren berücksichtigen."),
    ("Betriebliche Effizienz",   "be·TRIEP·li·che e·fi·TSI·ENTS", "Die Fähigkeit eines Unternehmens, Ressourcen optimal zu nutzen, um Gewinne zu maximieren."),
    ("Wirtschaftswachstum",      "WIRT·schafts·wachs·tum",        "Die Zunahme der wirtschaftlichen Aktivität und des Produktionspotenzials einer Volkswirtschaft."),
    ("Markteffizienz",           "MARKT·e·fi·zi·ents",            "Die Hypothese, dass alle verfügbaren Informationen in den Preisen von Vermögenswerten reflektiert sind."),
    ("Aktionär",                 "ak·tsio·NÄÄR",                  "Eine Person oder Institution, die Aktien eines Unternehmens besitzt."),
    ("Holdinggesellschaft",      "HOL·ding·ge·zel·shaft",         "Ein Unternehmen, dessen Hauptzweck in der Verwaltung von Beteiligungen an anderen Unternehmen besteht."),
    ("Dividendenrendite",        "di·vi·DEN·den·ren·di·te",       "Das Verhältnis der Dividende einer Aktie zu ihrem aktuellen Preis, ausgedrückt in Prozent."),
    ("Wachstumsaktien",          "WACHS·tums·ak·tsi·en",          "Aktien von Unternehmen, die überdurchschnittlich schnell wachsen."),
    ("Value-Aktien",             "WÄ·ljuu AK·tsi·en",             "Aktien, die als unterbewertet angesehen werden und ein großes Potenzial für Kurssteigerungen bieten."),
    ("Rückstellung",             "RÜCK·stel·lung",                "Ein Betrag, der zur Deckung künftiger Verpflichtungen oder erwarteter Verluste reserviert wird."),
    ("Eigenkapital",             "EI·gen·ka·pi·tal",              "Das Kapital, das von den Eigentümern eines Unternehmens zur Verfügung gestellt wird."),
    ("Fremdkapital",             "FREMT·ka·pi·tal",               "Kapital, das einem Unternehmen von externen Kreditgebern zur Verfügung gestellt wird."),
    ("Cashflow",                 "KÄSH·flo",                      "Der Nettobetrag der liquiden Mittel, der in einem bestimmten Zeitraum in ein Unternehmen fließt oder herausfließt."),
    ("Depot",                    "de·PO",                         "Ein Konto, auf dem Wertpapiere und andere Investitionen gehalten werden."),
    ("Finanzierungsrunde",       "fi·nan·TSI·rungs·run·de",       "Ein Prozess, bei dem ein Unternehmen Kapital von Investoren sammelt, oft in mehreren Phasen.")
]

let geschichteWörterListe: [(word: String, pronunciation: String, definition: String)] = [
    ("Renaissance",              "re·ne·SANS",                    "Eine kulturelle Bewegung des 14.–17. Jahrhunderts, die eine Rückbesinnung auf antike Werte und Kunst brachte."),
    ("Aufklärung",               "AUF·klä·rung",                  "Eine intellektuelle Bewegung des 17. und 18. Jahrhunderts, die Vernunft und Wissen über Tradition und Glauben stellte."),
    ("Imperialismus",            "im·pe·ria·LIS·mus",             "Die Politik eines Landes, seine Macht und seinen Einfluss über andere Länder durch Kolonialisierung oder militärische Eroberung auszubauen."),
    ("Kolonialismus",            "ko·lo·nia·LIS·mus",             "Die Praxis der Kontrolle und Besiedlung fremder Gebiete durch eine Nation."),
    ("Revolution",               "re·vo·lu·TSI·on",               "Ein radikaler und schneller Wandel eines politischen Systems oder gesellschaftlicher Strukturen."),
    ("Feudalismus",              "foi·da·LIS·mus",                "Ein soziales und wirtschaftliches System im Mittelalter, in dem Landbesitz und Treueverhältnisse zentral waren."),
    ("Bürgerkrieg",              "BÜR·ger·krieg",                 "Ein interner Krieg zwischen verschiedenen Gruppen innerhalb eines Landes."),
    ("Humanismus",               "hu·ma·NIS·mus",                 "Eine intellektuelle Bewegung, die den Menschen und seine Fähigkeiten in den Mittelpunkt stellte, besonders während der Renaissance."),
    ("Totalitarismus",           "to·ta·li·ta·RIS·mus",           "Ein politisches System, das die totale Kontrolle über das öffentliche und private Leben der Bürger ausübt."),
    ("Konstitution",             "kon·sti·tu·TSI·on",             "Ein Dokument, das die grundlegenden Prinzipien und Regeln einer Regierung oder Organisation festlegt."),
    ("Industrialismus",          "in·dus·tri·a·LIS·mus",          "Ein Gesellschaftsmodell, das auf industrieller Produktion basiert und die Mechanisierung und Massenproduktion betont."),
    ("Kalter Krieg",             "KAL·ter KRIEG",                 "Eine Zeit geopolitischer Spannungen zwischen den USA und der Sowjetunion nach dem Zweiten Weltkrieg."),
    ("Diktatur",                 "dik·ta·TUUR",                   "Eine Regierungsform, in der eine Person oder eine kleine Gruppe die absolute Kontrolle hat und politische Opposition unterdrückt."),
    ("Sozialismus",              "so·tsia·LIS·mus",               "Ein politisches und wirtschaftliches System, das soziale Eigentumsformen und die Umverteilung des Reichtums fördert."),
    ("Nationalismus",            "na·tsio·na·LIS·mus",            "Eine Ideologie, die das Interesse und die Identität einer Nation über andere legt."),
    ("Sklaverei",                "skla·ve·REI",                   "Ein System, in dem Menschen als Eigentum anderer Menschen behandelt und zur Arbeit gezwungen werden."),
    ("Mittelalter",              "MIT·tel·al·ter",                "Eine historische Periode in Europa, die grob vom 5. bis zum 15. Jahrhundert reicht."),
    ("Kreuzzüge",                "KROITZ·tsü·ge",                 "Militärische Expeditionen, die im Mittelalter von europäischen Christen unternommen wurden, um das Heilige Land zu erobern."),
    ("Entkolonialisierung",      "ent·ko·lo·nia·li·SI·rung",      "Der Prozess, durch den koloniale Staaten ihre Unabhängigkeit erlangen."),
    ("Sumerer",                  "su·ME·rer",                     "Eine der frühesten Zivilisationen, die im südlichen Mesopotamien lebte und für die Erfindung der Keilschrift bekannt ist."),
    ("Pharao",                   "FA·ra·o",                       "Der Titel für die monarchischen Herrscher des alten Ägyptens, oft als göttlich betrachtet."),
    ("Konquista",                "kon·KWIS·ta",                   "Die spanische Eroberung und Kolonisierung von großen Teilen Amerikas im 16. Jahrhundert."),
    ("Römisches Recht",          "RÖ·mi·shes RECHT",              "Das Rechtssystem, das im antiken Rom entstanden ist und bis heute Einfluss auf viele moderne Rechtssysteme hat."),
    ("Byzantinisches Reich",     "by·zan·TI·ni·shes REICH",       "Der östliche Teil des Römischen Reiches, der nach dem Fall des Weströmischen Reiches fortbestand."),
    ("Reformation",              "re·for·ma·TSI·on",              "Eine religiöse Bewegung im 16. Jahrhundert, die zur Spaltung der römisch-katholischen Kirche und zur Entstehung des Protestantismus führte."),
    ("Absolutistische Monarchie","ab·so·lu·TIS·ti·she mo·nar·CHIE","Eine Regierungsform, in der der Monarch nahezu uneingeschränkte Macht hat und durch keine Gesetze eingeschränkt ist."),
    ("Feudalordnung",            "foi·DAL·ord·nung",              "Ein gesellschaftliches System des Mittelalters, gekennzeichnet durch eine Hierarchie von Landbesitzern und Lehnsmännern."),
    ("Weimarer Republik",        "VAI·ma·rer re·pu·BLIK",         "Die erste deutsche Demokratie, die von 1919 bis 1933 bestand und unter extremem politischen Druck stand."),
    ("Französische Revolution",  "fran·ZÖ·si·she re·vo·lu·TSI·on","Eine gesellschaftliche und politische Umwälzung in Frankreich (1789–1799), die die Monarchie stürzte und moderne demokratische Werte verbreitete."),
    ("Industrielle Revolution",  "in·dus·tri·EL·le re·vo·lu·TSI·on","Eine tiefgreifende wirtschaftliche und gesellschaftliche Transformation im 18./19. Jahrhundert durch Mechanisierung und Dampfkraft.")
]

let politikWörterListe: [(word: String, pronunciation: String, definition: String)] = [
    ("Demokratie",               "de·mo·kra·TIE",                 "Ein Regierungssystem, in dem das Volk durch Wahlen an der politischen Entscheidungsfindung teilnimmt."),
    ("Diktatur",                 "dik·ta·TUUR",                   "Ein Regierungssystem, in dem eine Einzelperson oder Gruppe absolute Macht hat und politische Opposition unterdrückt."),
    ("Gewaltenteilung",          "ge·VAL·ten·tei·lung",           "Das Prinzip, staatliche Macht auf Legislative, Exekutive und Judikative aufzuteilen, um Machtmissbrauch zu verhindern."),
    ("Parlamentarismus",         "par·la·men·ta·RIS·mus",         "Ein Regierungssystem, in dem die Regierung dem Parlament gegenüber verantwortlich ist und von dessen Vertrauen abhängt."),
    ("Föderalismus",             "fö·de·ra·LIS·mus",              "Ein Staatsaufbau, bei dem Kompetenzen zwischen einer Zentralregierung und Gliedstaaten aufgeteilt sind."),
    ("Souveränität",             "su·ve·rä·ni·TÄÄHT",             "Das höchste Recht eines Staates, über sein eigenes Territorium und seine inneren Angelegenheiten selbst zu bestimmen."),
    ("Opposition",               "o·po·si·TSI·on",                "Die politischen Kräfte, die einer Regierung oder einer Mehrheit kritisch gegenüberstehen und alternative Konzepte vertreten."),
    ("Lobbyismus",               "lo·by·IS·mus",                  "Die gezielte Einflussnahme von Interessengruppen auf politische Entscheidungsträger."),
    ("Plebiszit",                "ple·bi·TSIT",                   "Eine direkte Abstimmung des Volkes über eine politische Frage oder Entscheidung."),
    ("Rechtsstaatlichkeit",      "RECHTS·shtaht·lich·kait",       "Das Prinzip, dass staatliches Handeln an Recht und Gesetz gebunden ist und Bürger vor Willkür geschützt werden."),
    ("Verfassung",               "fer·FAS·sung",                  "Das grundlegende Rechtsdokument eines Staates, das die Staatsstruktur und Grundrechte der Bürger festlegt."),
    ("Fraktion",                 "frak·TSI·on",                   "Eine Gruppe von Abgeordneten im Parlament, die derselben Partei angehören oder politisch ähnliche Ziele verfolgen."),
    ("Wahlrecht",                "WAHL·recht",                    "Das Recht der Bürger, an Wahlen teilzunehmen und politische Vertreter zu wählen oder gewählt zu werden."),
    ("Koalition",                "ko·a·li·TSI·on",                "Ein politisches Bündnis zwischen zwei oder mehr Parteien, um gemeinsam eine Regierung zu bilden."),
    ("Vetomacht",                "VE·to·macht",                   "Das Recht einer Institution oder Person, Beschlüsse zu blockieren oder aufzuheben."),
    ("Politische Partei",        "po·LI·ti·she par·TAI",          "Eine Organisation, die bestimmte politische Ziele verfolgt und Kandidaten für öffentliche Ämter aufstellt."),
    ("Bürgerbeteiligung",        "BÜR·ger·be·tai·li·gung",        "Die aktive Teilnahme von Bürgerinnen und Bürgern an politischen Prozessen über Wahlen hinaus."),
    ("Sanktion",                 "sank·TSI·on",                   "Eine politische oder wirtschaftliche Strafmaßnahme gegen einen Staat oder eine Person zur Durchsetzung von Normen."),
    ("Diplomatie",               "dip·lo·ma·TIE",                 "Die Führung internationaler Beziehungen durch Verhandlungen und Abkommen statt durch Gewalt."),
    ("Menschenrechte",           "MEN·shen·rech·te",              "Grundlegende Rechte, die jedem Menschen unabhängig von Herkunft, Nationalität oder Status zustehen.")
]

let bildungWörterListe: [(word: String, pronunciation: String, definition: String)] = [
    ("Aphorismus",               "a·fo·RIS·mus",                  "Ein kurzer, prägnanter Gedanke, der eine tiefe Wahrheit in einem einzigen Satz ausdrückt."),
    ("Apotheose",                "a·po·te·O·se",                  "Die Erhebung einer Person oder Idee zur höchsten Vollkommenheit oder zur Vergöttlichung."),
    ("Axiom",                    "ak·si·OM",                      "Ein Grundsatz, der ohne Beweis als wahr angenommen wird und als Ausgangspunkt für weiteres Denken dient."),
    ("Chimäre",                  "shi·MÄ·re",                     "Ein unrealistischer Traum oder ein Trugbild, das sich bei näherer Betrachtung als unerfüllbar erweist."),
    ("Dialektik",                "di·a·LEK·tik",                  "Eine Denkmethode, die durch das Aufeinanderprallen gegensätzlicher Positionen zu einer höheren Erkenntnis gelangt."),
    ("Dichotomie",               "di·cho·to·MIE",                 "Die Einteilung eines Begriffs oder Sachverhalts in zwei einander ausschließende Gegensätze."),
    ("Dogma",                    "DOG·ma",                        "Ein Grundsatz oder eine Lehre, der als unumstößlich wahr gilt und nicht in Frage gestellt werden darf."),
    ("Emphase",                  "em·FA·se",                      "Besondere Betonung oder Nachdruck, um einem Ausdruck zusätzliche Eindringlichkeit zu verleihen."),
    ("Epiphanie",                "e·pi·fa·NIE",                   "Ein plötzlicher, oft überwältigender Moment der Erkenntnis oder des tiefen Verstehens."),
    ("Epistemologie",            "e·pis·te·mo·lo·GIE",            "Der Teilbereich der Philosophie, der sich mit den Grundlagen, dem Ursprung und den Grenzen menschlichen Wissens beschäftigt."),
    ("Euphemismus",              "oi·fe·MIS·mus",                 "Ein beschönigender oder abschwächender Ausdruck, der an Stelle eines als unangenehm empfundenen Wortes verwendet wird."),
    ("Hegemonie",                "he·ge·mo·NIE",                  "Die dominierende Vorherrschaft eines Staates, einer Gruppe oder einer Idee über andere."),
    ("Hybris",                   "HY·bris",                       "Übermäßige Selbstüberschätzung und Anmaßung, die oft zu einem tragischen Scheitern führt."),
    ("Idiosynkrasie",            "i·di·o·syn·kra·SIE",            "Eine ausgeprägte persönliche Eigenart oder Überempfindlichkeit, die jemanden von anderen unterscheidet."),
    ("Immanenz",                 "i·ma·NENTS",                    "Das Innewohnen einer Eigenschaft oder Kraft in etwas, im Gegensatz zur Transzendenz."),
    ("Kognition",                "kog·ni·TSI·on",                 "Die Gesamtheit der mentalen Prozesse wie Wahrnehmung, Denken, Erinnern und Problemlösen."),
    ("Kontemplation",            "kon·tem·pla·TSI·on",            "Tiefes, ruhiges Nachsinnen und geistige Versenkung in einen Gedanken oder eine Frage."),
    ("Kosmopolit",               "kos·mo·po·LIT",                 "Eine Person, die sich als Weltbürger versteht und sich in verschiedenen Kulturen gleichermaßen zu Hause fühlt."),
    ("Latenz",                   "la·TENTS",                      "Ein verborgener, noch nicht sichtbarer Zustand oder ein schlummerndes Potenzial, das noch nicht zum Ausdruck gekommen ist."),
    ("Luzidität",                "lu·tsi·di·TÄÄHT",               "Geistige Klarheit und Durchsichtigkeit des Denkens, oft auch das Bewusstsein im Traum."),
    ("Metaphysik",               "me·ta·fy·SIK",                  "Der Bereich der Philosophie, der sich mit den grundlegenden Fragen nach dem Sein, der Wirklichkeit und der Existenz befasst."),
    ("Nihilismus",               "ni·hi·LIS·mus",                 "Eine Weltanschauung, die alle überlieferten Werte, Normen und Sinngebungen grundsätzlich verneint."),
    ("Ontologie",                "on·to·lo·GIE",                  "Das Teilgebiet der Philosophie, das sich mit dem Wesen und der Struktur des Seins und der Wirklichkeit befasst."),
    ("Paradigma",                "pa·ra·DIG·ma",                  "Ein grundlegendes Denk- und Erklärungsmodell, das den Rahmen für wissenschaftliches Arbeiten in einer Epoche bildet."),
    ("Paradox",                  "pa·ra·DOKS",                    "Eine Aussage, die scheinbar widersprüchlich oder absurd ist, bei genauerer Betrachtung jedoch eine tiefe Wahrheit enthält."),
    ("Paternalismus",            "pa·ter·na·LIS·mus",             "Das bevormundende Eingreifen in die Entscheidungsfreiheit anderer, vermeintlich zu deren eigenem Wohl."),
    ("Pleonasmus",               "ple·o·NAS·mus",                 "Die Verwendung eines überflüssigen, bedeutungsgleichen Zusatzwortes, wie zum Beispiel 'weißer Schimmel'."),
    ("Pragmatismus",             "prag·ma·TIS·mus",               "Eine Denkrichtung, die den Wert einer Idee nach ihrer praktischen Nützlichkeit und Anwendbarkeit beurteilt."),
    ("Prokrastination",          "pro·kras·ti·na·TSI·on",         "Das systematische Aufschieben von Aufgaben zugunsten angenehmerer Tätigkeiten, trotz bekannter negativer Folgen."),
    ("Redundanz",                "re·dun·DANTS",                  "Das Vorhandensein von überflüssigen, sich wiederholenden Informationen oder Elementen in einem System oder Text."),
    ("Relativismus",             "re·la·ti·VIS·mus",              "Die philosophische Auffassung, dass Wahrheit, Moral und Wissen immer abhängig von einem kulturellen oder persönlichen Standpunkt sind."),
    ("Rhetorik",                 "RE·to·rik",                     "Die Kunst der wirkungsvollen und überzeugenden Rede, die Sprache gezielt zur Beeinflussung einsetzt."),
    ("Serendipität",             "se·ren·di·pi·TÄÄHT",            "Das zufällige Entdecken wertvoller oder angenehmer Dinge, die man gar nicht gesucht hatte."),
    ("Solipsismus",              "so·lip·SIS·mus",                "Die philosophische These, dass nur das eigene Bewusstsein mit Sicherheit existiert und die Außenwelt unbeweisbar ist."),
    ("Syllogismus",              "sy·lo·GIS·mus",                 "Ein logischer Schluss, bei dem aus zwei Prämissen zwingend eine Schlussfolgerung abgeleitet wird."),
    ("Tautologie",               "tau·to·lo·GIE",                 "Eine Aussage, die durch bloße Wiederholung desselben Gedankens in anderen Worten scheinbar etwas aussagt."),
    ("Teleologie",               "te·le·o·lo·GIE",                "Die Lehre, dass Handlungen und Entwicklungen auf ein Ziel oder einen Zweck hin ausgerichtet sind."),
    ("Transzendenz",             "tran·ssen·DENTS",               "Das Überschreiten der Grenzen menschlicher Erfahrung und Erkenntnis hin zu etwas Höherem oder Unbedingtem."),
    ("Utopie",                   "u·to·PIE",                      "Der Entwurf einer idealen, vollkommenen Gesellschaft, die in der Realität (noch) nicht existiert."),
    ("Vulnerabilität",           "vul·ne·ra·bi·li·TÄÄHT",         "Verletzlichkeit und Empfänglichkeit für Schaden — sowohl im menschlichen als auch im technischen Kontext.")
]
